CREATE DATABASE geolocalizacion CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER 'usergeo'@'localhost' identified by 'geolocalizacion123';
GRANT ALL PRIVILEGES ON geolocalizacion.* TO 'usergeo'@'localhost';
FLUSH PRIVILEGES;

INSERT INTO centroinvestigacion_area VALUES ('1', 'Físico-Matemáticas y Ciencias de la Tierra');
INSERT INTO centroinvestigacion_area VALUES ('2', 'Biología y Química');
INSERT INTO centroinvestigacion_area VALUES ('3', 'Medicina y Ciencias de la Salud');
INSERT INTO centroinvestigacion_area VALUES ('4', 'Ciencias de la Conducta y la Educación');
INSERT INTO centroinvestigacion_area VALUES ('5', 'Humanidades');
INSERT INTO centroinvestigacion_area VALUES ('6', 'Ciencias Sociales');
INSERT INTO centroinvestigacion_area VALUES ('7', 'Ciencias de Agricultura, Agropecuarias, Forestales y de Ecosistemas');
INSERT INTO centroinvestigacion_area VALUES ('8', 'Ingenierías y Desarrollo Tecnológico');
INSERT INTO centroinvestigacion_area VALUES ('9', 'Interdiciplinaria');


INSERT INTO centroinvestigacion_municipio VALUES ('1' , 'Apozol');
INSERT INTO centroinvestigacion_municipio VALUES ('2' , 'Apulco');
INSERT INTO centroinvestigacion_municipio VALUES ('3' , 'Atolinga');
INSERT INTO centroinvestigacion_municipio VALUES ('4' , 'Benito Juárez');
INSERT INTO centroinvestigacion_municipio VALUES ('5' , 'Calera');
INSERT INTO centroinvestigacion_municipio VALUES ('6' , 'Cañitas de Felipe Pescador');
INSERT INTO centroinvestigacion_municipio VALUES ('7' , 'Concepción del Oro');
INSERT INTO centroinvestigacion_municipio VALUES ('8' , 'Cuauhtémoc');
INSERT INTO centroinvestigacion_municipio VALUES ('9' , 'Chalchihuites');
INSERT INTO centroinvestigacion_municipio VALUES ('10' , 'Fresnillo');
INSERT INTO centroinvestigacion_municipio VALUES ('11' , 'Trinidad García de la Cadena');
INSERT INTO centroinvestigacion_municipio VALUES ('12' , 'Genaro Codina');
INSERT INTO centroinvestigacion_municipio VALUES ('13' , 'General Enrique Estrada');
INSERT INTO centroinvestigacion_municipio VALUES ('14' , 'General Francisco R. Murguía');
INSERT INTO centroinvestigacion_municipio VALUES ('15' , 'El Plateado de Joaquín Amaro');
INSERT INTO centroinvestigacion_municipio VALUES ('16' , 'General Pánfilo Natera');
INSERT INTO centroinvestigacion_municipio VALUES ('17' , 'Guadalupe');
INSERT INTO centroinvestigacion_municipio VALUES ('18' , 'Huanusco');
INSERT INTO centroinvestigacion_municipio VALUES ('19' , 'Jalpa');
INSERT INTO centroinvestigacion_municipio VALUES ('20' , 'Jerez');
INSERT INTO centroinvestigacion_municipio VALUES ('21' , 'Jiménez del Teul');
INSERT INTO centroinvestigacion_municipio VALUES ('22' , 'Juan Aldama');
INSERT INTO centroinvestigacion_municipio VALUES ('23' , 'Juchipila');
INSERT INTO centroinvestigacion_municipio VALUES ('24' , 'Loreto');
INSERT INTO centroinvestigacion_municipio VALUES ('25' , 'Luis Moya');
INSERT INTO centroinvestigacion_municipio VALUES ('26' , 'Mazapil');
INSERT INTO centroinvestigacion_municipio VALUES ('27' , 'Melchor Ocampo');
INSERT INTO centroinvestigacion_municipio VALUES ('28' , 'Mezquital del Oro');
INSERT INTO centroinvestigacion_municipio VALUES ('29' , 'Miguel Auza');
INSERT INTO centroinvestigacion_municipio VALUES ('30' , 'Momax');
INSERT INTO centroinvestigacion_municipio VALUES ('31' , 'Monte Escobedo');
INSERT INTO centroinvestigacion_municipio VALUES ('32' , 'Morelos');
INSERT INTO centroinvestigacion_municipio VALUES ('33' , 'Moyahua de Estrada');
INSERT INTO centroinvestigacion_municipio VALUES ('34' , 'Nochistlán de Mejía');
INSERT INTO centroinvestigacion_municipio VALUES ('35' , 'Noria de Ángeles');
INSERT INTO centroinvestigacion_municipio VALUES ('36' , 'Ojocaliente');
INSERT INTO centroinvestigacion_municipio VALUES ('37' , 'Pánuco');
INSERT INTO centroinvestigacion_municipio VALUES ('38' , 'Pinos');
INSERT INTO centroinvestigacion_municipio VALUES ('39' , 'Río Grande');
INSERT INTO centroinvestigacion_municipio VALUES ('40' , 'Sain Alto');
INSERT INTO centroinvestigacion_municipio VALUES ('41' , 'El Salvador');
INSERT INTO centroinvestigacion_municipio VALUES ('42' , 'Sombrerete');
INSERT INTO centroinvestigacion_municipio VALUES ('43' , 'Susticacán');
INSERT INTO centroinvestigacion_municipio VALUES ('44' , 'Tabasco');
INSERT INTO centroinvestigacion_municipio VALUES ('45' , 'Tepechitlán');
INSERT INTO centroinvestigacion_municipio VALUES ('46' , 'Tepetongo');
INSERT INTO centroinvestigacion_municipio VALUES ('47' , 'Teúl de González Ortega');
INSERT INTO centroinvestigacion_municipio VALUES ('48' , 'Tlaltenango de Sánchez Román');
INSERT INTO centroinvestigacion_municipio VALUES ('49' , 'Valparaíso');
INSERT INTO centroinvestigacion_municipio VALUES ('50' , 'Vetagrande');
INSERT INTO centroinvestigacion_municipio VALUES ('51' , 'Villa de Cos');
INSERT INTO centroinvestigacion_municipio VALUES ('52' , 'Villa García');
INSERT INTO centroinvestigacion_municipio VALUES ('53' , 'Villa González Ortega');
INSERT INTO centroinvestigacion_municipio VALUES ('54' , 'Villa Hidalgo');
INSERT INTO centroinvestigacion_municipio VALUES ('55' , 'Villanueva');
INSERT INTO centroinvestigacion_municipio VALUES ('56' , 'Zacatecas');
INSERT INTO centroinvestigacion_municipio VALUES ('57' , 'Trancoso');
INSERT INTO centroinvestigacion_municipio VALUES ('58' , 'Santa María de la Paz');