# Generated by Django 4.0.2 on 2022-06-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='CentroInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=150, unique=True, verbose_name='Direccion')),
                ('latitud', models.CharField(max_length=20, unique=True)),
                ('longitud', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True, verbose_name='Telefono')),
                ('sitioWeb', models.CharField(blank=True, max_length=100, unique=True)),
                ('imagen', models.ImageField(upload_to='media')),
                ('enfoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='centroinvestigacion.enfoque', verbose_name='Enfoque')),
            ],
        ),
    ]
