# Generated by Django 4.0.2 on 2022-05-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centroinvestigacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CetnroInvestigacion',
            new_name='CentroInvestigacion',
        ),
    ]
