# Generated by Django 4.0.2 on 2022-07-14 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centroinvestigacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='centroinvestigacion',
            name='subAreaEnfoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centroinvestigacion.enfoque', verbose_name='SubArea'),
        ),
        migrations.AlterField(
            model_name='centroinvestigacion',
            name='areaEnfoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centroinvestigacion.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='enfoque',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='centroinvestigacion.area', verbose_name='Enfoque'),
        ),
    ]
