# Generated by Django 4.0.2 on 2022-06-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroinvestigacion', '0002_alter_centroinvestigacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroinvestigacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
