# Generated by Django 4.0.2 on 2022-05-22 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centroinvestigacion', '0003_alter_centroinvestigacion_enfoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroinvestigacion',
            name='enfoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='centroinvestigacion.enfoque', verbose_name='Enfoque'),
        ),
    ]
