# Generated by Django 4.0.2 on 2022-05-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroinvestigacion', '0004_alter_centroinvestigacion_enfoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfoque',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
